global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
  
  - job_name: 'monitoring'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['monitoring:8080']